### ISSUE TITLE
Swift Compiler Error in Cordova on Mac

### ISSUE THREAD

**Issue by secondtononeinc** [Maxim-Kolmogorov/cordova-plugin-push-notifications#3]
upon building, getting error:

Swift Compiler Error
    ......./Plugins/cordova-plugin-push-notifications/PushNotification.swift:7:30: Cannot find type 'AppDelegate' in scope

it's line 7 in the PushNotification.swift file causing the error:

1. import UserNotifications
2. 
3. var PushNotificationPluginToken = ""
4. let PushNotificationQueue = DispatchQueue(label: "pluginPushNotificationQueue", attributes: .concurrent)
5. let PushNotificationSemaphore = DispatchSemaphore(value: 0)
6.
7. @objc(AppDelegate) extension AppDelegate {     <-- here is the error "Cannot find type 'AppDelegate' in scope"

any ideas / help?

cordova v10 in xcode 12.4 on macos 10.15.7

**Comment by Maxim-Kolmogorov** [comment]
Cordova v10, Xcode 12.5.1, macOS 11.5.1 - none errors. 

Try "cordova platform rm ios" and "cordova platform add ios".

May OS not have created the Bridging-Header.h file due to the absence of the cordova-plugin-add-swift-support plugin. 
In general, the essence of the error is that Swift does not see the Objective-C code. You can try updating Xcode.
